variables:
#    NMC_FE1_SLURM_PARAMETERS: " --nodes=1 --cpus-per-task=1 --partition=ecp-p9-4v100 -t 6:00:00"
    NMC_FE1_SLURM_PARAMETERS: " --nodes=1 --ntasks-per-node=6 --partition=ecp-p9-4v100 --ntasks=6 -t 6:00:00"
#    SCHEDULER_PARAMETERS:  "-N1 -p ecp-p9-4v100 --extra-node-info=*:*:* -t 0:30:00 srun --pty bash --login"
stages:
    - build
# <<: *slurm
.slurm: &slurm
#    tags: ['nmc', 'slurm', 'xx-testing', 'dosequis']
    tags: ['nmc-xxfe1-sched-001']   
build:
    stage: build
    # Will inherit the .slurm: &slurm
    <<: *slurm
    script:
        - echo "Running build"
        - echo "this is a test"
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ecp/sw/opt/ppc64le/linux-centos7-power9le/gcc-8.3.0/gettext-0.19.8.1-l2kvcy6fvcejwrxdrsyf5br5mqolyxs7/lib
        - srun env | grep SLURM_JOB_NAME
        - whoami
        - echo "HOSTNAME=$HOSTNAME"
#        - source ~mrajan/.bashrc
#        - . set_modules_p9.sh
#        - module load mpi/openmpi3-ppc64le
        - ml load gcc/8.3.0
        - ml load openmpi
        - ml load cmake/3.14.5
        - ml list
        - ml avail openmpi
        - echo "Check type of available disk drives\n"
        - df -T
#
#
        - CI_PROJ_DIR=${PWD}
        - echo "CI_PROJ_DIR="${CI_PROJ_DIR}
# running 1 ctest process to build HDF5 without tools or examples and skip running tests.
        - HDF5_VER=`bin/h5vers`
        - ln -s . hdf5-$HDF5_VER
        - ln -s config/cmake/scripts/CTestScript.cmake .
        - ln -s config/cmake/scripts/HDF5config.cmake .
        - ln -s config/cmake/scripts/HDF5options.cmake .
        - echo 'set (MAX_PROC_COUNT 8)' >> config/cmake/scripts/HDF5options.cmake
        - echo 'set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_BUILD_TOOLS:BOOL=OFF")' >> config/cmake/scripts/HDF5options.cmake
        - echo 'set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DHDF5_BUILD_EXAMPLES:BOOL=OFF")' >> config/cmake/scripts/HDF5options.cmake
        - echo 'set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DMPIEXEC_NUMPROC_FLAG:STRING=-n")' >> config/cmake/scripts/HDF5options.cmake
        - echo 'set (ADD_BUILD_OPTIONS "${ADD_BUILD_OPTIONS} -DMPIEXEC_MAX_NUMPROCS:STRING=6")' >> config/cmake/scripts/HDF5options.cmake
        - SKIP_TESTS="-E '"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-btree2"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-cache"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-earray"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-evict_on_close"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-fheap"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-objcopy"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-set_extent"
        - SKIP_TESTS=$SKIP_TESTS"|H5TEST-testhdf5-base"
        - SKIP_TESTS=$SKIP_TESTS"'"
        - ctest -S HDF5config.cmake,SITE_BUILDNAME_SUFFIX="1.13.0-openmpi-gcc/8.3.0-Linux-4.18.0-80.7.2.el7.ppc64le-ppc64le",BUILD_GENERATOR=Unix,LOCAL_SUBMIT=true,MODEL=HPC ${SKIP_TESTS} -C Release -VV
#        - ctest . -S HDF5config.cmake,SITE_BUILDNAME_SUFFIX="1.13.0-openmpi-gcc/8.3.0-Linux-4.18.0-80.7.2.el7.ppc64le-ppc64le",MPI=true,BUILD_GENERATOR=Unix,LOCAL_SUBMIT=true,MODEL=HPC,LOCAL_SKIP_TEST=true
# run ctest command for only MPI (parallel) tests
#        - cd build
#        - ctest .  -R 'MPI_TEST_' -C Release -T test
#        - . .gitlab/nnsa.sh
#        - ls -ltr
#        - ls -ltr ./CI
#      look at the dirs to see how the build worked
        - echo $PWD
#        - cd ..
#        - echo $PWD
    artifacts:
        paths:
#           - zlib-1.2.11/
#           - hdf5-1.10.5/
    only: 
       - web
    variables:
        NMC_FE1_SLURM_PARAMETERS: " --nodes=1 --ntasks-per-node=6 --partition=ecp-p9-4v100 --ntasks=6 -t 6:00:00"
#NMC_FE1_SLURM_PARAMETERS: " --nodes=1 --cpus-per-task=1 --partition=ecp-p9-4v100 -t 6:00:00"
#NMC_FE1_SLURM_PARAMETERS: "-N1 -p ecp-p9-4v100 -t 1:30:00"
#    tags: ['nmc', 'slurm', 'xx-testing', 'dosequis']
    tags: ['nmc-xxfe1-sched-001']

