name: hdf5 dev autools CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel. We just have one job, but the matrix items defined below will
# run in parallel.
jobs:
    call-workflow-special-autotools:
      name: "Autotools Special Workflows"
      uses: ./.github/workflows/main-auto-spc.yml

    call-parallel-special-autotools:
      name: "Autotools Parallel Special Workflows"
      uses: ./.github/workflows/main-auto-par-spc.yml

    call-debug-parallel-autotools:
      name: "Autotools Parallel Workflows"
      uses: ./.github/workflows/main-auto-par.yml
      with:
            build_mode: "debug"

    call-release-parallel-autotools:
      name: "Autotools Parallel Workflows"
      uses: ./.github/workflows/main-auto-par.yml
      with:
            build_mode: "production"

    call-debug-thread-autotools:
      name: "Autotools Debug Thread-Safety Workflows"
      uses: ./.github/workflows/main-auto.yml
      with:
            thread_safety: enable
            build_mode: "debug"

    call-release-thread-autotools:
      name: "Autotools Release Thread-Safety Workflows"
      uses: ./.github/workflows/main-auto.yml
      with:
            thread_safety: enable
            build_mode: "production"

    call-debug-autotools:
      name: "Autotools Debug Workflows"
      uses: ./.github/workflows/main-auto.yml
      with:
            thread_safety: disable
            build_mode: "debug"

    call-release-autotools:
      name: "Autotools Release Workflows"
      uses: ./.github/workflows/main-auto.yml
      with:
            thread_safety: disable
            build_mode: "production"

    call-release-auto-intel:
      name: "Autotools Intel Workflows"
      uses: ./.github/workflows/intel-auto.yml
      with:
            build_mode: "production"

    call-release-auto-nvhpc:
      name: "Autotools nvhpc Workflows"
      uses: ./.github/workflows/nvhpc-auto.yml
      with:
            build_mode: "production"
