name: cve 1.14

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ hdf5_1_14_3 ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: CVE regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Autotools Dependencies (Linux)
        run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin
      - name: Install HDF5
        run: |
          ./autogen.sh
          ./configure --prefix=/usr/local --disable-tests
          make
          sudo make install
      - name: Checkout CVE test repository
        uses: actions/checkout@v4
        with:
          repository: HDFGroup/cve_hdf5
          path: cve_hdf5
      - name: Run regression tests
        run: |
          cd cve_hdf5
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
          ./test_hdf5_cve.sh /usr/local/bin ./cve_out
