name: hdf5 1.14 autotools julia

on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

jobs:
  julia_build_and_test:
    name: "julia ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake libtool libtool-bin libaec-dev
          sudo apt-get install doxygen graphviz
          sudo apt install -y zlib1g-dev libcurl4-openssl-dev libjpeg-dev wget curl bzip2
          sudo apt install -y m4 flex bison cmake libzip-dev openssl build-essential

      - name: Autotools Configure
        shell: bash
        run: |
          sh ./autogen.sh
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          $GITHUB_WORKSPACE/configure \
            --enable-build-mode=${{ inputs.build_mode }} \
            --disable-fortran \
            --enable-shared \
            --disable-parallel \
            --prefix=/tmp

      - name: Autotools Build
        shell: bash
        run: |
          make -j3
        working-directory: ${{ runner.workspace }}/build

      - name: Install HDF5
        shell: bash
        run: |
          make install
        working-directory: ${{ runner.workspace }}/build

      - name: Install julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
          arch: 'x64'

      - name: Get julia hdf5 source
        uses: actions/checkout@v4.1.1
        with:
          repository: JuliaIO/HDF5.jl
          path: .

      - name: Generate LocalPreferences
        run: |
          echo '[HDF5]' >> LocalPreferences.toml
          echo 'libhdf5 = "/tmp/lib/libhdf5.so"' >> LocalPreferences.toml
          echo 'libhdf5_hl = "/tmp/lib/libhdf5_hl.so"' >> LocalPreferences.toml

      - uses: julia-actions/julia-buildpkg@latest

      - name: Julia Run Tests
        uses: julia-actions/julia-runtest@latest
        env:
          JULIA_DEBUG: Main
