name: lin jl

on:
  workflow_dispatch:
  push:
  pull_request:
<<<<<<< HEAD
    branches: [ hdf5_1_14 ]
=======
    branches: [ develop ]
>>>>>>> 967db7f... Add Julia GitHub Actions. (#4123)
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Julia:
    name: Julia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
<<<<<<< HEAD
=======
          repository: HDFGroup/hdf5
>>>>>>> 967db7f... Add Julia GitHub Actions. (#4123)
          path: hdf5
      - name: Install HDF5
        run: |
          cd hdf5
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp ..
          make -j
          make install
          cd ..

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
          arch: 'x64'
      - uses: actions/checkout@v4
        with:
          repository: JuliaIO/HDF5.jl
          path: .

      - name: Generate LocalPreferences
        run: |
          echo '[HDF5]' >> LocalPreferences.toml
          echo 'libhdf5 = "/tmp/lib/libhdf5.so"' >> LocalPreferences.toml
          echo 'libhdf5_hl = "/tmp/lib/libhdf5_hl.so"' >> LocalPreferences.toml

      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_DEBUG: Main
